create table books (
    id int8 generated by default as identity,
    name varchar(100) not null,
    calendar_date DATE not null,
    status varchar(50) not null,
    reader_id int8 references users(id) on delete cascade,
    primary key (id)
);

create table users (
    id int8 generated by default as identity,
    username varchar(255) not null,
    password varchar(255) not null,
    role varchar(255) not null,
    active boolean not null,
    primary key (id)
);

CREATE TABLE user_books(
    user_id INTEGER REFERENCES users(id) ON DELETE CASCADE
    book_id INTEGER REFERENCES books(id) ON DELETE CASCADE
);